Preliminary Copy To Main Panel support

diff --git a/NsCDE/libexec/subpanel_menuitem_props b/NsCDE/libexec/subpanel_menuitem_props
--- a/NsCDE/libexec/subpanel_menuitem_props
+++ b/NsCDE/libexec/subpanel_menuitem_props
@@ -278,6 +278,85 @@ function manage_entry
    fi
 }
 
+function copy_to_main_panel
+{
+         entry_to_copy=$(egrep -h "^S${subpid},ENTRY,*" "$FVWM_USERDIR/Subpanels.actions" | sed -n "${entryid}p")
+         if [ "x$entry_to_copy" == "x" ]; then
+            entry_to_copy=$(egrep -h "^S${subpid},ENTRY,*" "$NCDE_ROOT/config/Subpanels.actions" | sed -n "${entryid}p")
+         fi
+         if [ "x$entry_to_copy" == "x" ]; then
+            echo "ERROR: subpanel_menuitem_props (copy_to_main_panel): internal error. No entry in system Subpanels.actons file."
+            exit 10
+         fi
+         echo "$entry_to_copy" | tail -1 | while IFS="," read smark emark title type icon cmd
+         do
+            for content in "$title" "$icon" "$cmd"
+            do
+               if [ "x$content" == "x" ]; then
+                  echo "ERROR: subpanel_menuitem_props (copy_to_main_panel): empty title, icon or command definition."
+                  exit 10
+               fi
+            done
+
+            find_appropriate_icon "$icon"
+            fp_m1="Btn${subpid},$icon,M1,${cmd%% *},$cmd"
+            fp_m3="Btn${subpid},,M3,FVWM,f_FrontPanelPropsMenu 4 $title"
+            if [ -r "$FVWM_USERDIR/FrontPanel.actions" ]; then
+               $NSCDE_ROOT/bin/ised -c "/^Btn${subpid},\(.*\)\?,M\(1\|3\)/d" -f $FVWM_USERDIR/FrontPanel.actions
+            fi
+            echo "$fp_m1" | head -1 >> "$FVWM_USERDIR/FrontPanel.actions"
+            echo "$fp_m3" | head -1 >> "$FVWM_USERDIR/FrontPanel.actions"
+            FvwmCommand "SendToModule FrontPanel ChangeButton Btn${subpid} Icon \"$icon\""
+         done
+}
+
+function find_appropriate_icon
+{
+   # First, try similar path with 48x48 instead of 32x32 or similar:
+   try_icon=$(echo "$1" | sed 's/\/[1-9]\+x[1-9]\+\//\/48x48\//g')
+   if [ -r "$try_icon" ]; then
+      icon="$try_icon"
+      break
+   fi
+
+   if [ -d "$HOME/.local/share/icons" ]; then
+      try_try_icon=$(find "$HOME/.local/share/icons" -type f -name "${1##*/}" | head -1)
+      if [ $(echo "$try_try_icon" | egrep "48x48") != "" ]; then
+         icon="$try_try_icon"
+         break
+      fi
+      m_to_l=$(echo "$1" | sed 's/\.m\.\(xpm\|pm\)/\.l\.\1/g')
+      try_try_icon=$(find "$HOME/.local/share/icons" -type f -name "${m_to_l##*/}" | head -1)
+      if [ -r "$try_try_icon" ]; then
+         icon="$try_try_icon"
+         break
+      fi
+   fi
+
+   try_icon_p=$(echo "$1" | sed 's/\.m\.\(xpm\|pm\)/\.l\.\1/g')
+   try_icon="${try_icon_p##*/}"
+   if [ -r "$NSCDE_ROOT/share/icons/CDE/$try_icon" ]; then
+      icon="$NSCDE_ROOT/share/icons/CDE/$try_icon"
+      break
+   fi
+   if [ -r "$NSCDE_ROOT/share/icons/NsCDE/$try_icon" ]; then
+      icon="$NSCDE_ROOT/share/icons/NsCDE/$try_icon"
+      break
+   fi
+   if [ -r "$FVWM_USERDIR/icons/NsCDE/$try_icon" ]; then
+      icon="$FVWM_USERDIR/icons/NsCDE/$try_icon"
+      break
+   fi
+   if [ -r "$FVWM_USERDIR/icons/CDE/$try_icon" ]; then
+      icon="$FVWM_USERDIR/icons/CDE/$try_icon"
+      break
+   fi
+   if [ -r "$FVWM_USERDIR/icons/$try_icon" ]; then
+      icon="$FVWM_USERDIR/icons/$try_icon"
+      break
+   fi
+}
+
 function delete_confirm
 {
    if [[ -n $DISPLAY ]]; then
@@ -291,7 +370,7 @@ function exec_entry
    FvwmCommand "SendToModule NsCDE-Subpanel${subpid} PressButton Btn-${subpid}-${entryid}"
 }
 
-while getopts p:s:a:t:ed Option
+while getopts p:s:a:t:edc Option
 do
    case $Option in
       p)
@@ -314,6 +393,9 @@ do
       ;;
       d)
          delete_confirm
+      ;;
+      c)
+         copy_to_main_panel
       ;;
    esac
 done
