Preliminary FVWM3 Support work.

diff --git a/NsCDE/bin/nscde b/NsCDE/bin/nscde
--- a/NsCDE/bin/nscde
+++ b/NsCDE/bin/nscde
@@ -13,7 +13,7 @@ if [ -z $HOME ]; then
    echo "Error: HOME not set." >&2
    exit 2
 else
-   export NSCDE_VERSION="1.0rc25"
+   export NSCDE_VERSION="1.0rc26"
 fi
 
 # Either print version and exit, or construct main options for and output
@@ -51,10 +51,15 @@ fi
 
 # Find fvwm(1) binary. This is a critical point.
 # We cannot continue without main workforce.
-FVWM_BIN=$(whence -p fvwm)
-if (($? != 0)); then
-   echo "Error: cannot detect fvwm in $PATH"
-   exit 3
+if [ ! -x "$FVWM_BIN" ]; then
+   FVWM_BIN=$(whence -p fvwm)
+   if (($? != 0)); then
+      FVWM_BIN=$(whence -p fvwm3)
+      if (($? != 0)); then
+         echo "Error: cannot detect fvwm or fvwm3 in $PATH"
+         exit 3
+      fi
+   fi
 fi
 
 # Handle our X defaults if it exists.
