Further work on FHS standards #9

diff --git a/NsCDE/libexec/NsCDE/fontmgr b/NsCDE/libexec/NsCDE/fontmgr
--- a/NsCDE/libexec/NsCDE/fontmgr
+++ b/NsCDE/libexec/NsCDE/fontmgr
@@ -11,6 +11,11 @@ if [ -z $NSCDE_ROOT ]; then
    exit 2
 fi
 
+if [ -z $NSCDE_DATADIR ]; then
+   echo "Error: NSCDE_DATADIR is not set. Exiting."
+   exit 2
+fi
+
 type -p fc-list > /dev/null
 if (($? != 0)); then
    echo "Error: fc-list command not found."
@@ -27,6 +32,11 @@ function findfontsets
 {
    if [ -z $NSCDE_ROOT ]; then
       echo "No NSCDE_ROOT defined. Exiting."
+      exit 2
+   fi
+
+   if [ -z $NSCDE_DATADIR ]; then
+      echo "No NSCDE_DATADIR defined. Exiting."
       exit 2
    fi
 
diff --git a/NsCDE/libexec/NsCDE/fp_manage_subpanel b/NsCDE/libexec/NsCDE/fp_manage_subpanel
--- a/NsCDE/libexec/NsCDE/fp_manage_subpanel
+++ b/NsCDE/libexec/NsCDE/fp_manage_subpanel
@@ -15,6 +15,16 @@ if [ ! -e "$NSCDE_ROOT" ]; then
    exit 5
 fi
 
+if [ -z $NSCDE_DATADIR ]; then
+   echo "Error: NSCDE_DATADIR is not set cannot continue."
+   exit 4
+fi
+
+if [ ! -e "$NSCDE_DATADIR" ]; then
+   echo "Error: NSCDE_DATADIR does not exist. Cannot continue."
+   exit 5
+fi
+
 if [ -z $FVWM_USERDIR ]; then
    echo "Error: FVWM_USERDIR is not set cannot continue."
    exit 6
