Migration script tuning and localization

diff --git a/nscde_tools/migrate_nscde_1x_2x.in b/nscde_tools/migrate_nscde_1x_2x.in
--- a/nscde_tools/migrate_nscde_1x_2x.in
+++ b/nscde_tools/migrate_nscde_1x_2x.in
@@ -1,19 +1,38 @@
 #!@KSH@
 
+#
+# This file is a part of the NsCDE - Not so Common Desktop Environment
+# Author: Hegel3DReloaded
+# Licence: GPLv3
+#
+
+export TEXTDOMAINDIR="$NSCDE_ROOT/share/locale"
+export TEXTDOMAIN="nscde-migrate-1x_to_2x"
+
+whence -q gettext
+if (($? == 0)); then
+   text="gettext -s"
+   textn="gettext -sn"
+else
+   text="print"
+   textn="print -rn"
+fi
+
 if [ -f "$HOME/.NsCDE/.migrate_nscde_1x_2x_norun" ] && [ "x$1" == "x-i" ]; then
+   $textn "File "; echo -ne "$HOME/.NsCDE/.migrate_nscde_1x_2x_norun"; $text " exists."
+   $text "This script is refusing to run in the interactive mode while that file exists."
    exit 0
 fi
 
-trap "" INT
-trap "" TERM
-trap "" QUIT
-trap "" ABRT
-trap "" PIPE
-trap "" USR1
-trap "" USR2
-trap "" HUP SIGHUP
-
 if [ "x$1" == "x-i" ]; then
+   trap "" INT
+   trap "" TERM
+   trap "" QUIT
+   trap "" ABRT
+   trap "" PIPE
+   trap "" USR1
+   trap "" USR2
+   trap "" HUP SIGHUP
    interactive=1
 else
    interactive=0
@@ -21,7 +40,7 @@ fi
 
 cd "$HOME/.NsCDE"
 if (( $? != 0)); then
-   echo "Error: cannot change directory to $HOME/.NsCDE"
+   $textn "Error: cannot change directory to"; echo "$HOME/.NsCDE"
    sleep 3
    exit 4
 fi
@@ -30,7 +49,7 @@ ISED="$NSCDE_TOOLSDIR/ised"
 OS=$(uname -s)
 
 if [ ! -x "$ISED" ]; then
-   echo "Error: ised script wrapper not found. Check if NSCDE_TOOLSDIR is set."
+   $text "Error: ised script wrapper not found. Check if \$NSCDE_TOOLSDIR is set."
    sleep 3
    exit 5
 fi
@@ -40,15 +59,16 @@ function backup_current_dot_nscde
    if [ -d "$HOME/.NsCDE" ]; then
       confdir_size=$(du -ks "$HOME/.NsCDE" | awk '{ print $1 }')
       if (( $confdir_size > 204800 )); then
-         echo "Error: your $HOME/.NsCDE directory has more then 200 MB. Something appears to be"
-         echo "wrong with your NsCDE profile. Examine your profile, or back it up manually, and"
-         echo "rerun migration script like \"$0 -B\"."
+         $textn "Error: your "; echo -ne "$HOME/.NsCDE "; $text "directory has more then 200 MB. Something appears to be"
+         $text "wrong with your NsCDE profile. Examine your profile, or back it up manually, and"
+         $text "rerun migration script without \"-i\" option."
          sleep 3
          exit 2
       else
          cd "$HOME"
          if (($? != 0)); then
-            echo "Error: cannot change directory to $HOME"
+            $textn "Error: cannot change directory to "; echo "${HOME}."
+	    sleep 3
             exit 6
          else
             stamp=$(date +%d-%m-%Y-%H-%M-%S)
@@ -68,15 +88,15 @@ function backup_current_dot_nscde
             ;;
             esac
             if (($RETVAL1 == 0)); then
-               echo "Backup copy of $HOME/.NsCDE saved as $HOME/dot_NsCDE_${stamp}.tar."
-               cd -
+               $textn "Backup copy of "; echo -ne "$HOME/.NsCDE "; $textn "saved as "; echo "$HOME/dot_NsCDE_${stamp}.tar."
+               cd - > /dev/null
                if (($? != 0)); then
-                  echo "Error: cannot change directory back to $HOME/.NsCDE"
+                  $textn "Error: cannot change directory back to "; echo "$HOME/.NsCDE"
                   sleep 3
                   exit 5
                fi
             else
-               echo "Error: backing up $HOME/.NsCDE exited with exit status ${RETVAL1}."
+               $textn "Error: backing up "; echo -ne "$HOME/.NsCDE"; $textn " exited with exit status "; echo "${RETVAL1}."
                sleep 3
                exit 3
             fi
@@ -118,11 +138,13 @@ function rename_config_files
       new_oc="${new_oc2}"
 
       if [ -r "$HOME/.NsCDE/${oc}" ] [ -h "$HOME/.NsCDE/${oc}" ]; then
-         echo "Renaming $oc to $new_oc ..."
+         $textn "Renaming "; echo -ne "$oc"; $textn " to "; echo "$new_oc ..."
          mv -f "$oc" "$new_oc"
          RETVAL=$?
          if (($RETVAL != 0)); then
-            echo "Error: Renaming ${oc} to ${new_oc} returned error ${RETVAL}."
+            $textn "Error: Renaming "; echo -ne "${oc}"; $textn " to "; echo -ne "${new_oc}"; $textn " returned error "; echo "${RETVAL}."
+	    sleep 3
+	    exit 7
          fi
       fi
    done
@@ -135,11 +157,13 @@ function rename_config_files
       new_og="${new_og2}"
 
       if [ -r "$HOME/.NsCDE/${og}" ] || [ -h "$HOME/.NsCDE/${og}" ]; then
-         echo "Renaming $og to $new_og ..."
+         $textn "Renaming "; echo -ne "$og"; $textn " to "; echo "$new_og ..."
          mv -f "$og" "$new_og"
          RETVAL=$?
          if (($RETVAL != 0)); then
-            echo "Error: Renaming ${og} to ${new_og} returned error ${RETVAL}."
+            $textn "Error: Renaming "; echo -ne "${og}"; $textn " to "; echo -ne "${new_og}"; $textn " returned error "; echo "${RETVAL}."
+	    sleep 3
+	    exit 7
          fi
       fi
    done
@@ -152,40 +176,42 @@ function rename_config_files
       new_ol="${new_ol2}"
 
       if [ -r "$HOME/.NsCDE/${ol}" ] || [ -h "$HOME/.NsCDE/${ol}" ]; then
-         echo "Renaming $ol to $new_ol ..."
+         $textn "Renaming "; echo -ne "$ol"; $textn " to "; echo "$new_ol ..."
          mv -f "$ol" "$new_ol"
          RETVAL=$?
          if (($RETVAL != 0)); then
-            echo "Error: Renaming ${ol} to ${new_ol} returned error ${RETVAL}."
+            $textn "Error: Renaming "; echo -ne "${ol}"; $textn " to "; echo -ne "${new_ol}"; $textn " returned error "; echo "${RETVAL}."
+	    sleep 3
+	    exit 7
          fi
       fi
    done
 
    # Handle renaming of pager config.
    if [ -f "Pager-LocalPager.fvwmconf" ]; then
-      echo "Renaming Pager-LocalPager.fvwmconf to LocalPager.fvwmconf"
+      $text "Renaming Pager-LocalPager.fvwmconf to LocalPager.fvwmconf"
       mv -f Pager-LocalPager.fvwmconf LocalPager.fvwmconf
    fi
    if [ -f "Pager-LocalPager.fvwmlocal" ]; then
-      echo "Renaming Pager-LocalPager.fvwmlocal to LocalPager.fvwmlocal"
+      $text "Renaming Pager-LocalPager.fvwmlocal to LocalPager.fvwmlocal"
       mv -f Pager-LocalPager.fvwmlocal LocalPager.fvwmlocal
    fi
    if [ -f "Pager-WspLocPager.fvwmconf" ]; then
-      echo "Renaming Pager-WspLocPager.fvwmconf to WspLocPager.fvwmconf"
+      $text "Renaming Pager-WspLocPager.fvwmconf to WspLocPager.fvwmconf"
       mv -f Pager-WspLocPager.fvwmconf WspLocPager.fvwmconf
    fi
    if [ -f "Pager-WspLocPager.fvwmlocal" ]; then
-      echo "Renaming Pager-WspLocPager.fvwmlocal to WspLocPager.fvwmlocal"
+      $text "Renaming Pager-WspLocPager.fvwmlocal to WspLocPager.fvwmlocal"
       mv -f Pager-WspLocPager.fvwmlocal WspLocPager.fvwmlocal
    fi
 
    # Handle local for of the FrontPanel configuration if exists.
    if [ -f "FrontPanel.fvwmconf" ]; then
       if [ "x$FVWM_IS_FVWM3" == "x1" ]; then
-         echo "Renaming FrontPanel.fvwmconf to FrontPanel.fvwm3.fvwmconf"
+         $text "Renaming FrontPanel.fvwmconf to FrontPanel.fvwm3.fvwmconf"
          mv -f FrontPanel.fvwmconf FrontPanel.fvwm3.fvwmconf
       else
-         echo "Renaming FrontPanel.fvwmconf to FrontPanel.fvwm2.fvwmconf"
+         $text "Renaming FrontPanel.fvwmconf to FrontPanel.fvwm2.fvwmconf"
          mv -f FrontPanel.fvwmconf FrontPanel.fvwm2.fvwmconf
       fi
    fi
@@ -197,7 +223,7 @@ function rename_config_files
          base_fontset=$(readlink ${fo})
          if [ ! -f "fontsets/${base_fontset##*/}" ]; then
             if [ -f "${NSCDE_DATADIR}/fontsets/${base_fontset##*/}" ]; then
-              echo "Relinking ${fo} to ${NSCDE_DATADIR}/fontsets/${base_fontset##*/}."
+              $textn "Relinking "; echo -ne "${fo}"; $textn " to "; echo "${NSCDE_DATADIR}/fontsets/${base_fontset##*/}."
               ln -sf "${NSCDE_DATADIR}/fontsets/${base_fontset##*/}" "${fo}"
             fi
          fi
@@ -473,21 +499,21 @@ function replace_confnames_in_files {
    for oce in $old_confs_escaped
    do
       oce_new=$(echo "${oce}" | sed 's/^NsCDE-//g; s/\.conf/\.fvwmconf/g')
-      echo "Changing ${oce/\\/} occurences to ${oce_new/\\/} in all regular files inside ~/.NsCDE"
+      $textn "Changing "; echo -ne "${oce/\\/}"; $textn " occurences to "; echo -ne "${oce_new/\\/}"; $text " in all regular files inside ~/.NsCDE"
       find . -xdev -type f ! -name "*.xpm" ! -name "*.png" ! -name "*.pm" ! -name "*.log" ! -name .BGdefault ! -name .Exec-History ! -name "*.pid" -exec $ISED -c "s/${oce}/${oce_new}/g" -f {} \;
    done
 
    for oge in $old_genconfs_escaped
    do
       oge_new=$(echo "${oge}" | sed 's/^NsCDE-//g; s/\.conf/\.fvwmgen/g')
-      echo "Changing ${oge/\\/} occurences to ${oge_new/\\/} in all regular files inside ~/.NsCDE"
+      $textn "Changing "; echo -ne "${oge/\\/}"; $textn " occurences to "; echo -ne "${oge_new/\\/}"; $text " in all regular files inside ~/.NsCDE"
       find . -xdev -type f ! -name "*.xpm" ! -name "*.png" ! -name "*.pm" ! -name "*.log" ! -name .BGdefault ! -name .Exec-History ! -name "*.pid" -exec $ISED -c "s/${oge}/${oge_new}/g" -f {} \;
    done
 
    for ole in $old_locals_escaped
    do
       ole_new=$(echo "${ole}" | sed 's/^NsCDE-//g; s/\.local/\.fvwmlocal/g')
-      echo "Changing ${ole/\\/} occurences to ${ole_new/\\/} in all regular files inside ~/.NsCDE"
+      $textn "Changing "; echo -ne "${ole/\\/}"; $textn " occurences to "; echo -ne "${ole_new/\\/}"; $text " in all regular files inside ~/.NsCDE"
       find . -xdev -type f ! -name "*.xpm" ! -name "*.png" ! -name "*.pm" ! -name "*.log" ! -name .BGdefault ! -name .Exec-History ! -name "*.pid" -exec $ISED -c "s/${ole}/${ole_new}/g" -f {} \;
    done
 }
@@ -504,7 +530,7 @@ function walk_and_change_pathnames_in_files
 
    for ftp in $files_to_process
    do
-      echo "Processing $ftp with pathname replacements for NsCDE 2.0"
+      $textn "Processing "; echo -ne "$ftp"; $text " with pathname replacements for NsCDE 2.0"
       replace_pathnames_in_files "$ftp"
    done
 }
@@ -512,54 +538,60 @@ function walk_and_change_pathnames_in_files
 function preface
 {
    echo ""
-   echo "It appears that you have ~/.NsCDE profile from NsCDE 1.x installation."
-   echo "This migration script is here to convert your old profile to match"
-   echo "new file names and paths of NsCDE 2.x."
+   $text "It appears that you have ~/.NsCDE profile from NsCDE 1.x installation."
+   $text "This migration script is here to convert your old profile to match"
+   $text "new file names and paths of NsCDE 2.x."
    echo ""
-   echo "This migration process wants to do this actions:"
+   $text "This migration script wants to perform the following actions:"
    echo ""
-   echo "* Backup your existing ~/.NsCDE into ~/dot_NsCDE_dd_mm_YY_HH_MM_SS.tar"
-   echo "  just in case if anything goes wrong."
+   $text "* Backup your existing ~/.NsCDE into ~/dot_NsCDE_dd_mm_YY_HH_MM_SS.tar"
+   $text "  just in case if anything goes wrong."
    echo ""
-   echo "* Rename old names NsCDE-XYZ.conf into XYZ.fvwm(conf|gen) in ~/.NsCDE"
+   $text "* Rename old names NsCDE-XYZ.conf into XYZ.fvwm(conf|gen) in ~/.NsCDE"
    echo ""
-   echo "* Rename NsCDE-XYZ.local into XYZ.fvwmlocal in ~/.NsCDE"
+   $text "* Rename NsCDE-XYZ.local into XYZ.fvwmlocal in ~/.NsCDE"
    echo ""
-   echo "* Examine regular configrations and scripts in ~/.NsCDE and replace"
-   echo "  old names and paths to their new pathnames."
+   $text "* Examine regular configrations and scripts in ~/.NsCDE and replace"
+   $text "  old names and paths to their new pathnames."
    echo ""
-   echo "* Restart NsCDE in normal mode."
+   $text "* Restart NsCDE in normal mode."
    echo ""
 
-   PS3="Choice (1, 2 or 3): "
-   
-   select action in abort skiponce migrate
+   PS3=$(gettext -s "Choose 1, 2 or 3: ")
+
+   select action in "$($text 'Migrate')" "$($text 'Skip Once')" "$($text 'Abort')"
    do
       case $action in
-      abort) 
-         print "No automatic migration will be performed. This migration process will"
-         print "not run again. You will have to handle migration manually - either by"
-         print "running this script in non-interactive or interactive mode again after"
-         print "removing $HOME/.NsCDE/.migrate_nscde_1x_2x_norun or by editing files."
-
+      "$($text 'Abort')")
+	 print ""
+         $text "No automatic migration will be performed. This migration process will"
+         $text "not run again. You will have to handle migration manually - either by"
+         $text "running this script in non-interactive or interactive mode again after"
+         $textn "removing "; echo "$HOME/.NsCDE/.migrate_nscde_1x_2x_norun"
+	 $text "or by editing files."
+	 print ""
+	 $textn "Press return to cancel migration and exit. "
+         read ret
          touch $HOME/.NsCDE/.migrate_nscde_1x_2x_norun
-         sleep 9
          exit 0
       ;;
    
-      skiponce)
-         print "No automatic migration will be performed. This migration process will"
-         print "run again on next log in. To disable, choose abort action from the menu."
-         print "This migration process will now restart NsCDE in normal mode. Many of"
-         print "your configurations will not work properly until files are not renamed"
-         print "and pathnames consolidated in them."
-
-         sleep 10
+      "$($text 'Skip Once')")
+	 print ""
+         $text "No automatic migration will be performed. This migration script will"
+         $text "run again on next log in. To disable, choose Abort action from the menu."
+         $text "This migration process will now restart NsCDE in normal mode. Many of"
+         $text "your configurations will not work properly until files are not renamed"
+         $text "and pathnames consolidated in them."
+	 print ""
+	 $textn "Press return to escape migration for now. "
+         read ret
          exit 0
       ;;
    
-      migrate)
-         print "Starting migration of your NsCDE profile ..."
+      "$($text 'Migrate')")
+         echo ""
+         $text "Starting migration of your NsCDE profile ..."
          sleep 1
          echo ""
          sleep 1
@@ -569,8 +601,9 @@ function preface
          replace_confnames_in_files
          walk_and_change_pathnames_in_files
 
-         echo "Done. Restarting ..."
-         sleep 3
+         $text "Done. Press return to restart NsCDE with migrated profile."
+	 read ret
+	 $text "Restarting ..."
 
          # Make sure there is no garbage here
          rm -f  $HOME/.NsCDE/Subpanels.fvwm3.fvwmgen
@@ -578,12 +611,13 @@ function preface
 
          # Restart finally
          $NSCDE_ROOT/bin/nscde_fvwmclnt Restart
+	 sleep 2
 
          exit $?
       ;;
    
-      *) 
-         print "Please try again. Use 1, 2 or 3"
+      *)
+         $text "Please try again: type 1, 2 or 3"
       ;; 
       esac
    done
